### ISSUE TITLE
Token NRDP

### ISSUE THREAD

**Issue by Davidffry** [EyesOfNetworkCommunity/eyesofapplication#8]
Bonjour, 
étant nouveau dans la mise en place d'un EON, je souhaite tester la version EON4APP pour superviser les applications de ma machine Windows. 
Pour cela il est nécessaire de récupérer le Token NRDP ainsi que l'IP de la machine, pour cette dernière pas de souci mais par contre pour le NRDP où puis-je trouver l'information?
Concernant la visualisation des process en cours, où puis-je visualiser les éléments?
Merci pour votre retour.

**Comment by Guiona** [comment]
Bonjour,

Le token NRDP est défini dans le fichier "/srv/eyesofnetwork/nrdp/server/config.inc.php"
La valeur par défaut est "c25a488c6bdb787bb09c8789e458e22d" mais il est possible de la changer.
